### ISSUE TITLE
Chapter 11 | Simplified Explanation

### ISSUE THREAD

**Issue by Sai-Tam** [sherbold/intro-to-data-science#26]
> A bit simplified, the test statistics $t$ is the rescaled _difference_ between the two populations $X_1$ and $X_2$ such that this is the _difference_ to estimates the _difference_ of the means as if they were two standard normal distributions.

I don't find this explanation to be significantly simplified. Using the word difference three times in one sentence for me invokes confusion rather than clarity. Furthermore i assume there is a typo at 'difference to estimate**s** the difference'.
If this sentence could be rephrased a little bit it would be very helpful.

**Comment by sherbold** [comment]
I rephrased the sentence as follows.

> A bit simplified, the test statistics $t$ is the rescaled difference between the two populations $X_1$ and $X_2$ such that $t$ estimates the difference of the means as if they were two standard normal distributions..

Is this clearer?

**Comment by sherbold** [comment]
Closing this for now. Please reopen if this is still unclear.
