### ISSUE TITLE
Chapter 6 | Picking ϵ and minPts

### ISSUE THREAD

**Issue by Sai-Tam** [sherbold/intro-to-data-science#29]
>  Increasing minPts avoids small clusters but can also lead to no clusters or lots of noise if ϵ is too **large**.

I think the sentence above is faulty. In my understanding a large ϵ would include more points into the cluster and therefore reduce noise and force bigger clusters (as stated a couple sentences before). I assume "if ϵ is too small." is correct, since it is less likely to have minPts within a smaller range of ϵ and therefore exclude seperated points (noise) or prevent core points from forming (no points with minPts neighbors).

P.S.: I got lost in GitHub and posted this in https://github.com/sherbold/data-science-and-big-data-analytics please ignore the issue there

**Comment by sherbold** [comment]
Yes, indeed.
