### ISSUE TITLE
Chapter 7: Classification - Minor Error for Micro and Macro Averages 

### ISSUE THREAD

**Issue by FelixStein01** [sherbold/intro-to-data-science#44]
In chapter 7 - _Classification_, subchapter _Micro and Macro Averages_, second table (example with whale as positive class), the false positive whale is noted as 5, but should be 4 (sum of (_predicted whale, actual bear_), (_predicted whale, actual other_) = 1 + 3 = 4)

![grafik](https://user-images.githubusercontent.com/87033415/126899389-a9ad7c77-d886-48a5-a3cf-a79f3e276e1e.png)

**Comment by sherbold** [comment]
No, this is correct, because that is the sum of (actual whale, predicted bear) and (actual whale, predicted other).

**Comment by moritz-meier** [comment]
But something isn't quite right. The multiclass table adds up to 136 instances and the binary table adds up to 137 instances. I think @FelixStein01  is right, FPwhale = (pred whale, actual bear) + (pred whale, actual other) = 4
